# Generated by Django 4.1.4 on 2023-01-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devsocial', '0005_mensaje_delete_modelbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
