# Generated by Django 4.1.4 on 2023-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsocial', '0006_delete_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='info',
            field=models.TextField(max_length=30),
        ),
    ]
