# Generated by Django 4.1.4 on 2023-02-02 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsocial', '0008_post_usuario_alter_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 1, 20, 21, 38, 236757)),
        ),
    ]
