# Generated by Django 4.1.4 on 2023-02-03 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsocial', '0009_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 21, 51, 47, 470395)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 2, 2)),
        ),
    ]
