# Generated by Django 4.1.4 on 2023-02-04 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsocial', '0010_alter_comentario_fecha_alter_post_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 4, 11, 53, 38, 30911)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 2, 4)),
        ),
    ]
