# Generated by Django 4.1.4 on 2023-02-04 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsocial', '0011_alter_comentario_fecha_alter_post_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.CharField(default='a', max_length=30),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 4, 14, 11, 28, 825081)),
        ),
    ]
