# Generated by Django 4.1.4 on 2023-02-04 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsocial', '0013_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 4, 18, 22, 19, 171808)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='info',
            field=models.TextField(max_length=60),
        ),
    ]
